#!/usr/bin/env python3
"""
Convert Brave/Chrome DevTools "Copy all" cookies (tab-separated table)
into Netscape cookies.txt format for yt-dlp.

Input: tab-separated rows with columns:
Name, Value, Domain, Path, Expires/Max-Age, Size, HttpOnly, Secure, SameSite, ...
Output: Netscape cookie file.
"""

from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path
from typing import Optional


def parse_expiry(value: str) -> int:
    v = (value or "").strip()
    if not v or v.lower() == "session":
        return 0
    # Example: 2026-08-01T01:22:33.958Z
    v = v.replace("Z", "+00:00")
    try:
        return int(dt.datetime.fromisoformat(v).timestamp())
    except Exception:
        return 0


def convert_line(line: str) -> Optional[str]:
    if not line.strip():
        return None
    parts = line.split("\t")
    if len(parts) < 5:
        return None
    name = parts[0].strip()
    value = parts[1]
    domain = parts[2].strip()
    path = parts[3].strip() or "/"
    expires = parts[4].strip()
    http_only = (parts[6].strip() == "✓") if len(parts) > 6 else False
    secure = (parts[7].strip() == "✓") if len(parts) > 7 else False

    if not name or not domain:
        return None

    exp_ts = parse_expiry(expires)
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    secure_flag = "TRUE" if secure else "FALSE"
    domain_out = f"#HttpOnly_{domain}" if http_only else domain
    return f"{domain_out}\t{include_subdomains}\t{path}\t{secure_flag}\t{exp_ts}\t{name}\t{value}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="Path to Brave/Chrome cookies export (tab-separated)")
    ap.add_argument("--output", required=True, help="Path to Netscape cookies.txt")
    args = ap.parse_args()

    in_path = Path(args.input)
    out_path = Path(args.output)

    raw = in_path.read_text(encoding="utf-8", errors="replace").splitlines()
    lines = []
    for line in raw:
        if line.lstrip().startswith("# Netscape"):
            # Already in Netscape format.
            out_path.write_text("\n".join(raw).rstrip() + "\n", encoding="utf-8")
            return 0
        converted = convert_line(line)
        if converted:
            lines.append(converted)

    header = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by convert_cookies_brave.py",
        "",
    ]
    out_path.write_text("\n".join(header + lines).rstrip() + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

